### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by billywongstuy** [wxiang54/softdev-hw04#1]
-The debugger for Flask was left on. This could be dangerous when running the program on a non-private server.

**Comment by wxiang54** [comment]
So delving deeper into this, the Flask application only runs on localhost as of now, so I think the debugger should be fine, since the reason for the fuss is that the debugger lets you execute arbitrary code on the host machine. If you're only running on localhost, you'd essentially be executing arbitrary code on your own machine, which is kinda pointless. 

Thanks you for the heads up, though! I'm bound to forget to turn the debugger off when I deploy on a live server in the future :cry:
